src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=256)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToOne(targetEntity=File::class, cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $croppedImageName;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private $croppedImageThumbnailName;

    /**
     * @ORM\OneToMany(targetEntity=ArticlePositionCategory::class, mappedBy="article", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"positionCategory" = "ASC"})
     */
    private $positionCategories;

    public function __construct()
    {
        $this->positionCategories = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getCategories()
    {
        $categories = [];
        foreach ($this->getPositionCategories() as $positionCategory) {
            $categories[] = $positionCategory->getCategory();
        }

        return $categories;
    }

    public function removeCategory($category)
    {
        foreach ($this->getPositionCategories() as $positionCategory) {
            if ($category === $positionCategory->getCategory()) {
                $this->removePositionCategory($positionCategory);
                $positionCategory->getCategory()->removePositionArticle($positionCategory);

                return true;
            }
        }

        return false;
    }

    public function computeSlug(SluggerInterface $slugger)
    {
        if (!$this->slug || '-' === $this->slug) {
            $this->slug = (string) $slugger->slug((string) $this)->lower();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getImage(): ?File
    {
        return $this->image;
    }

    public function setImage(?File $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCroppedImageName(): ?string
    {
        return $this->croppedImageName;
    }

    public function getCroppedImageAlt(): ?string
    {
        $alt = substr($this->croppedImageName, strpos($this->croppedImageName, '___') + 3);

        return substr($alt, 0, strpos($alt, '.'));
    }

    public function setCroppedImageName(?string $croppedImageName): self
    {
        $this->croppedImageName = $croppedImageName;

        return $this;
    }

    public function getCroppedImageThumbnailName(): ?string
    {
        return $this->croppedImageThumbnailName;
    }

    public function getCroppedImageThumbnailAlt(): ?string
    {
        $alt = substr($this->croppedImageThumbnailName, strpos($this->croppedImageThumbnailName, '___') + 3);

        return substr($alt, 0, strpos($alt, '.'));
    }

    public function setCroppedImageThumbnailName(?string $croppedImageThumbnailName): self
    {
        $this->croppedImageThumbnailName = $croppedImageThumbnailName;

        return $this;
    }

    /**
     * @return Collection|ArticlePositionCategory[]
     */
    public function getPositionCategories(): Collection
    {
        return $this->positionCategories;
    }

    public function addPositionCategory(ArticlePositionCategory $positionCategory): self
    {
        if (!$this->positionCategories->contains($positionCategory)) {
            $this->positionCategories[] = $positionCategory;
            $positionCategory->setArticle($this);
        }

        return $this;
    }

    public function removePositionCategory(ArticlePositionCategory $positionCategory): self
    {
        if ($this->positionCategories->removeElement($positionCategory)) {
            // set the owning side to null (unless already changed)
            if ($positionCategory->getArticle() === $this) {
                $positionCategory->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/Back/ArticleBatchType.php
<?php

namespace App\Form\Back;

use App\Entity\Article;
use App\Manager\Back\ArticleManager;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleBatchType extends AbstractType
{
    /**
     * @var ArticleManager     */
    private $articleManager;

    public function __construct(ArticleManager $articleManager)
    {
        $this->articleManager = $articleManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('articles', EntityType::class, [
                'label' => false,
                'choice_label' => false,
                'class' => Article::class,
                'choices' => $options['articles'],
                'expanded' => true,
                'multiple' => true,
            ])
            ->add('action', ChoiceType::class, [
                'label' => false,
                'placeholder' => 'Action',
                'choices' => [
                    'action.delete' => 'delete',
                ],
                'multiple' => false,
            ])
            ->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
                $result = $this->articleManager->validationBatchForm($event->getForm());
                if (true !== $result) {
                    $event->getForm()->addError(new FormError($result));
                }
            });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'articles' => null,
            'translation_domain' => 'back_messages',
        ]);
    }
}

src/Form/Back/ArticleCategoryBatchType.php
<?php

namespace App\Form\Back;

use App\Entity\ArticleCategory;
use App\Manager\Back\ArticleCategoryManager;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleCategoryBatchType extends AbstractType
{
    /**
     * @var ArticleCategoryManager     */
    private $articleCategoryManager;

    public function __construct(ArticleCategoryManager $articleCategoryManager)
    {
        $this->articleCategoryManager = $articleCategoryManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('article_categories', EntityType::class, [
                'label' => false,
                'choice_label' => false,
                'class' => ArticleCategory::class,
                'choices' => $options['article_categories'],
                'expanded' => true,
                'multiple' => true,
            ])
            ->add('action', ChoiceType::class, [
                'label' => false,
                'placeholder' => 'Action',
                'choices' => [
                    'action.delete' => 'delete',
                ],
                'multiple' => false,
            ])
            ->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
                $result = $this->articleCategoryManager->validationBatchForm($event->getForm());
                if (true !== $result) {
                    $event->getForm()->addError(new FormError($result));
                }
            });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'article_categories' => null,
            'translation_domain' => 'back_messages',
        ]);
    }
}

src/Form/Back/ArticleCategoryFilterType.php
<?php

namespace App\Form\Back;

use App\Manager\Back\ArticleCategoryManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleCategoryFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('search', TextType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => 'label.filter_search',
                ],
                'required' => false,
            ])
            ->add('number_by_page', IntegerType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => 'label.filter_number_by_page',
                ],
                'empty_data' => ArticleCategoryManager::NUMBER_BY_PAGE,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
            'method' => 'GET',
            'translation_domain' => 'back_messages',
        ]);
    }

    public function getBlockPrefix()
    {
        return 'filter';
    }
}

src/Form/Back/ArticleCategoryOrderCollectionType.php
<?php

namespace App\Form\Back;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleCategoryOrderCollectionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('categories', CollectionType::class, [
                'label' => false,
                'entry_options' => [
                    //'label' => false,
                ],
                'entry_type' => ArticleCategoryOrderType::class,
                'data' => $options['categories'],
                'allow_add' => false,
                'allow_delete' => false,
                'prototype' => false,
                'attr' => [
                    'class' => 'collection-selector',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'categories' => null,
            'translation_domain' => 'back_messages',
        ]);
    }

    public function finishView(\Symfony\Component\Form\FormView $view, \Symfony\Component\Form\FormInterface $form, array $options)
    {
        foreach ($view['categories']->children as $key => &$childView) {
            $childView->vars['label'] = $childView->vars['value']->getName();
        }
    }
}

src/Form/Back/ArticleCategoryOrderType.php
<?php

namespace App\Form\Back;

use App\Entity\ArticleCategory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleCategoryOrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('position', HiddenType::class, [
                'attr' => [
                    'class' => 'position',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ArticleCategory::class,
            'translation_domain' => 'back_messages',
        ]);
    }
}

src/Form/Back/ArticleCategoryType.php
<?php

namespace App\Form\Back;

use App\Entity\Article;
use App\Entity\ArticleCategory;
use App\Repository\ArticleCategoryRepository;
use App\Repository\ArticleRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleCategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'article_category.label.name',
            ])
            ->add('displayedHome', CheckboxType::class, [
                'label' => 'article_category.label.displayed_home',
                'required' => false,
            ])
            ->add('displayedMenu', CheckboxType::class, [
                'label' => 'article_category.label.displayed_menu',
                'required' => false,
            ])
            ->add('filterParentCategory', TextType::class, [
                'label' => 'article_category.label.filter_parent_category',
                'mapped' => false,
                'required' => false,
            ])
            ->add('parentCategory', EntityType::class, [
                'label' => 'article_category.label.parent_category',
                'class' => ArticleCategory::class,
                'query_builder' => function (ArticleCategoryRepository $er) {
                    return $er->createQueryBuilder('a')
                            ->orderBy('a.name', 'ASC');
                },
                'placeholder' => '---',
                'required' => false,
            ])
            ->add('articles', EntityType::class, [
                'label' => 'article_category.label.articles',
                'label_html' => true,
                'class' => Article::class,
                'query_builder' => function (ArticleRepository $er) {
                    return $er->createQueryBuilder('a')
                            ->orderBy('a.title', 'ASC');
                },
                'data' => $options['articles'],
                'multiple' => true,
                'expanded' => true,
                'mapped' => false,
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ArticleCategory::class,
            'translation_domain' => 'back_messages',
            'articles' => [],
        ]);
    }
}

templates/back/article/_category.html.twig
{% trans_default_domain 'back_messages' %}
    
<h{{ hn }}>{{ category }}</h{{ hn}}>
{% set hn = hn + 1 %}
{% for article in category.articles %}
    {% if article.id != article_id %}
        <h{{ hn }}>
            <a href="{{ path('back_article_read', { 'id': article.id }) }}">
                {{ article.title }}
            </a>
        </h{{ hn }}>
    {% endif %}
{% endfor %}
{% for subcategory in category.subcategories %}
    {% include 'back/article/_category.html.twig' with { 'article_id': article_id, 'category': subcategory, 'hn': hn } %}
{% endfor %}

templates/back/article/_script_categories.html.twig
{% trans_default_domain 'back_messages' %}
    
<script type="text/javascript">
    $( document ).ready( function () {
        $('#number_of_category_selected').html($('#category_list input[type="checkbox"]:checked').length);
        var displaySelectedCategories = function () {
            var ul = $('<ul class="list-unstyled"></ul>');
            $('#category_list input[type="checkbox"]:checked').each(function (i, input) {
                if ("" != $( 'label[for="' + $(input).attr('id') + '"]').text()) {
                    ul.append( '<li>' + $( 'label[for="' + $(input).attr('id') + '"]').text() + '</li>' );
                }
            });
            $( '#categories_selected' ).html(ul.html());
        };
        displaySelectedCategories();
        $('#categories_dropdown').on('show.bs.dropdown', function () {
            $( '#categories_selected' ).html("");
        });
        $('#categories_dropdown').on('hidden.bs.dropdown', function () {
            displaySelectedCategories();
        });
        $('#category_list').on('click', ':checkbox', function() {
            $('#number_of_category_selected').html($('#category_list input[type="checkbox"]:checked').length);
        });
        $('#categories_filter').on('keyup', function () {
            var filter = this.value.toUpperCase();
            $('#category_list').find('label').each(function (i, label) {
                if (filter == "" || label.innerText.toUpperCase().indexOf(filter) > -1) {
                    $( '#item_' + $(label).attr('for') ).show();
                    $($(label).parents('.form-group')[0]).show();
                } else {
                    $( '#item_' + $(label).attr('for') ).hide();
                    $($(label).parents('.form-group')[0]).hide();
                }
            });
        });
        $("#select_all").change(function() {
            if (this.checked) {
                $( '#category_list input[type="checkbox"]' ).each(function() {
                    this.checked=true;
                });
            } else {
                $( '#category_list input[type="checkbox"]' ).each(function() {
                    this.checked=false;
                });
            }
            $('#number_of_category_selected').html($('#category_list input[type="checkbox"]:checked').length);
        });
    });
</script>

templates/back/article/category_order.html.twig
{% trans_default_domain 'back_messages' %}
{% extends "back/layout.html.twig" %}

{% block title %}{{ 'article.category_order.title'|trans() }}{% endblock %}

{% block content %}
    <section class="pt-4 pb-4">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="h3">{{ 'article.category_order.h1'|trans() }}</h1>
                </div>
                <div class="col-sm-6 text-right">
                    <p>
                        <a href="{{ path('back_article_read', { 'id': article.id }) }}" class="btn btn-primary" role="button">
                            <i class="fas fa-reply"></i> {{ 'button.back'|trans() }}
                        </a>
                    </p>
                </div>
            </div>
            <hr>
            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ 'article.category_order.h2'|trans() }}</h2>
                    <div class="card-content p-2 mb-4">
                        {% form_theme form 'form/jquery.collection.html.twig' %}
                        {{ form_start(form) }}
                            {{ form_row(form.articlePositionCategories) }}
                            <button class="btn btn-primary btn-block">
                                <i class="far fa-paper-plane"></i> {{ 'button.submit'|trans() }}
                            </button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/jquery.collection.js') }}"></script>
    <script type="text/javascript">
        $('.collection-selector').collection({
            position_field_selector: '.position',
            // init_with_n_elements: 1,
            // min: 1,
            add_at_the_end: false,
            allow_add: false,
            allow_remove: false,
            allow_down: true,
            allow_up: true,
            // add: '<a href="#" class="btn bg-white text-primary button" title="{{ 'button.add'|trans() }}" role="button"><i class="fas fa-plus"></i></a>',
            // remove: '<a href="#" class="btn bg-white text-primary button" title="{{ 'button.remove'|trans() }}" role="button"><i class="fas fa-trash"></i></a>',
            up: '<a href="#" class="btn bg-white text-primary button" title="{{ 'button.up'|trans() }}" role="button"><i class="fas fa-arrow-up"></i></a>',
            down: '<a href="#" class="btn bg-white text-primary button" title="{{ 'button.down'|trans() }}" role="button"><i class="fas fa-arrow-down"></i></a>',
        });
    </script>
{% endblock %}

templates/back/article/read.html.twig
{% trans_default_domain 'back_messages' %}
{% extends "back/layout.html.twig" %}

{% set can_update = true %}
{% set can_delete = true %}

{% block title %}{{ 'article.read.title'|trans() }}{% endblock %}

{% block content %}
{% if can_delete %}
    <div id="delete" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modal_title" class="modal-title">{{ 'article.delete.modal_title'|trans() }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="X">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modal_body" class="modal-body">
                    <h6 id="modal_body_title"></h6>
                    <div class="alert alert-warning">
                        <strong>{{ 'delete.warning'|trans() }}</strong>
                    </div>
                </div>
                <div id="modal_footer" class="modal-footer">
                    {{ form_start(form_delete, {'attr': {'id': 'form_back_article_delete' }}) }}
                        <button type="submit" class="btn btn-danger">{{ 'button.delete'|trans() }}</button>
                    {{ form_end(form_delete) }}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'button.cancel'|trans() }}</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}
    <section class="pt-4 pb-4">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="h3">{{ 'article.read.h1'|trans({ '%identifier%': article }) }}</h1>
                </div>
                <div class="col-sm-6 text-right">
                    <p>
                        <a href="{{ path('back_article_search') }}" class="btn btn-primary" role="button">
                            <i class="fas fa-reply"></i> {{ 'button.back'|trans() }}
                        </a>
                        {% if can_update %}
                            <a href="{{ path('back_article_update', {'id': article.id}) }}" title="{{ 'button.update_title'|trans() }}"
                                class="btn btn-warning" aria-label="{{ 'button.update_title'|trans() }}" role="button">
                                <i class="fas fa-edit"></i>
                            </a>
                        {% endif %}
                        {% if can_delete %}
                            <a href="#" class="btn btn-danger btn-delete" data-toggle="modal" data-target="#delete"
                                data-title="{{ article }}" role="button"
                                data-path="{{ path('back_article_delete', { 'ids': {0: article.id}}) }}"
                                title="{{ 'button.delete_title'|trans() }}" aria-label="{{ 'button.delete_title'|trans() }}">
                                <i class="fas fa-times"></i>
                            </a>
                        {% endif %}
                        {% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_AGENT') and app.user.id == user.id) %}
                            <a href="{{ path('back_article_image_update', { 'id': article.id }) }}" class="btn btn-info" role="button">
                                <span>{{ 'article.button.update_image'|trans() }}</span>
                            </a>
                            <a href="{{ path('back_article_image_crop', { 'id': article.id }) }}" class="btn btn-info" role="button">
                                <span>{{ 'article.button.crop_image'|trans() }}</span>
                            </a>
                        {% endif %}
                        {% if article.positionCategories.count > 1 %}
                            <a href="{{ path('back_article_order_categories', { 'id': article.id }) }}" class="btn btn-primary">
                                <i class="fas fa-plus"></i>
                                {{ 'button.order'|trans() }}
                            </a>
                        {% endif %}
                    </p>
                </div>
            </div>
            <hr>
            <div class="d-flex flex-column flex-sm-row justify-content-between">
                {% if article.croppedImageName %}
                    <div class="text-center"><img src="/upload/{{ article.croppedImageName }}" alt="{{ article.croppedImageAlt }}" class="img-fluid"></div><br>
                {% endif %}
                <div class="card mt-4 mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ article.title }}</h2>
                        <div class="card-content">
                            
                            <ul class="list-unstyled">        
                                <li class="p-2 mb-2">
                                    <strong>{{ 'article.field.author'|trans() }} : </strong>{{ article.author }}                            
                                </li>
                                <li class="p-2 mb-2">
                                    <strong>{{ 'article.field.created_at'|trans() }} : </strong>{{ article.createdAt ? article.createdAt|format_datetime : '' }}
                                </li>
                                <li class="p-2 mb-2">
                                    <strong>{{ 'article.field.updated_at'|trans() }} : </strong>{{ article.updatedAt ? article.updatedAt|format_datetime : '' }}
                                </li>
                            </ul>
                        </div>
                    </div>        
                </div>
            </div>

            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ 'article.field.description'|trans() }}</h2>
                    <div class="card-content">
                        <p>{{ article.description|nl2br }}</p>
                    </div>
                </div>
            </div>

            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <div class="card-content">
                        <div class="text-justify">{{ article.content|raw }}</div>
                    </div>
                </div>
            </div>
            
            <div class="card mt-4 mb-4">
                <div class="card-body">
                    <div class="card-content">
                        {% for category in article.categories %}
                            {% include 'back/article/_category.html.twig' with { 'article_id': article.id, 'category': category, 'hn': 2 } %}
                        {% endfor %}
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if can_delete %}
        <script>
            $(document).ready(function(){
                $('.btn-delete').click(function(){
                    var title = $(this).attr('data-title');
                    var path = $(this).attr('data-path');
                    $('#form_back_article_delete').attr('action', path);
                    $('#modal_body_title').html("{{ 'delete.confirm'|trans() }} : <strong>"+title+"</strong>");
                });
            });
        </script>
    {% endif %}
{% endblock %}