src/Entity/ArticleCategory.php
<?php

namespace App\Entity;

use App\Repository\ArticleCategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @ORM\Entity(repositoryClass=ArticleCategoryRepository::class)
 */
class ArticleCategory
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $displayedMenu;

    /**
     * @ORM\Column(type="boolean")
     */
    private $displayedHome;

    /**
     * @ORM\Column(type="integer")
     */
    private $position;

    /**
     * @ORM\ManyToOne(targetEntity=ArticleCategory::class, inversedBy="subcategories", cascade={"persist"})
     */
    private $parentCategory;

    /**
     * @ORM\OneToMany(targetEntity=ArticleCategory::class, mappedBy="parentCategory", cascade={"persist"})
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $subcategories;

    /**
     * @ORM\OneToMany(targetEntity=ArticlePositionCategory::class, mappedBy="category", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({"positionArticle" = "ASC"})
     */
    private $positionArticles;

    public function __construct()
    {
        $this->position = 0;
        $this->displayedHome = false;
        $this->displayedMenu = false;
        $this->subcategories = new ArrayCollection();
        $this->positionArticles = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getParentCategories(array $parents = [])
    {
        if ($this->getParentCategory()) {
            $parents[] = $this->getParentCategory();

            return $this->getParentCategory()->getParentCategories($parents);
        }

        return $parents;
    }

    public function getDeep()
    {
        return count($this->getParentCategories());
    }

    public function getArticles()
    {
        $articles = [];
        foreach ($this->getPositionArticles() as $positionArticle) {
            $articles[] = $positionArticle->getArticle();
        }

        return $articles;
    }

    public function removeArticle($article)
    {
        foreach ($this->getPositionArticles() as $positionArticle) {
            if ($article === $positionArticle->getArticle()) {
                $this->removePositionArticle($positionArticle);
                $positionArticle->getArticle()->removePositionCategory($positionArticle);

                return true;
            }
        }

        return false;
    }

    public function computeSlug(SluggerInterface $slugger)
    {
        if (!$this->slug || '-' === $this->slug) {
            $this->slug = (string) $slugger->slug((string) $this)->lower();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDisplayedMenu(): ?bool
    {
        return $this->displayedMenu;
    }

    public function setDisplayedMenu(bool $displayedMenu): self
    {
        $this->displayedMenu = $displayedMenu;

        return $this;
    }

    public function getDisplayedHome(): ?bool
    {
        return $this->displayedHome;
    }

    public function setDisplayedHome(bool $displayedHome): self
    {
        $this->displayedHome = $displayedHome;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getParentCategory(): ?self
    {
        return $this->parentCategory;
    }

    public function setParentCategory(?self $parentCategory): self
    {
        $this->parentCategory = $parentCategory;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getSubcategories(): Collection
    {
        return $this->subcategories;
    }

    public function addSubcategory(self $subcategory): self
    {
        if (!$this->subcategories->contains($subcategory)) {
            $this->subcategories[] = $subcategory;
            $subcategory->setParentCategory($this);
        }

        return $this;
    }

    public function removeSubcategory(self $subcategory): self
    {
        if ($this->subcategories->removeElement($subcategory)) {
            // set the owning side to null (unless already changed)
            if ($subcategory->getParentCategory() === $this) {
                $subcategory->setParentCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ArticlePositionCategory[]
     */
    public function getPositionArticles(): Collection
    {
        return $this->positionArticles;
    }

    public function addPositionArticle(ArticlePositionCategory $positionArticle): self
    {
        if (!$this->positionArticles->contains($positionArticle)) {
            $this->positionArticles[] = $positionArticle;
            $positionArticle->setCategory($this);
        }

        return $this;
    }

    public function removePositionArticle(ArticlePositionCategory $positionArticle): self
    {
        if ($this->positionArticles->removeElement($positionArticle)) {
            // set the owning side to null (unless already changed)
            if ($positionArticle->getCategory() === $this) {
                $positionArticle->setCategory(null);
            }
        }

        return $this;
    }
}

src/Controller/Back/ArticleCategoryController.php
<?php

namespace App\Controller\Back;

use App\Entity\ArticleCategory;
use App\Entity\ArticlePositionCategory;
use App\Form\Back\ArticleCategoryBatchType;
use App\Form\Back\ArticleCategoryFilterType;
use App\Form\Back\ArticleCategoryOrderCollectionType;
use App\Form\Back\ArticleCategoryType;
use App\Form\Back\ArticlePositionCategoryOrderCollectionType;
use App\Manager\Back\ArticleCategoryManager;
use App\Repository\ArticleCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/back/article/category")
 */
class ArticleCategoryController extends AbstractController
{
    /**
     * @var ArticleCategoryRepository     */
    private $articleCategoryRepository;

    /**
     * @var ArticleCategoryManager     */
    private $articleCategoryManager;

    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(ArticleCategoryRepository $articleCategoryRepository, ArticleCategoryManager $articleCategoryManager, TranslatorInterface $translator)
    {
        $this->articleCategoryRepository = $articleCategoryRepository;
        $this->articleCategoryManager = $articleCategoryManager;
        $this->translator = $translator;
    }

    /**
     * @Route("/search", name="back_article_category_search", methods="GET|POST")
     */
    public function search(Request $request, Session $session)
    {
        $formFilter = $this->createForm(ArticleCategoryFilterType::class, null, ['action' => $this->generateUrl('back_article_category_search', [])]);
        $formFilter->handleRequest($request);
        $data = $this->articleCategoryManager->configFormFilter($formFilter)->getData();
        $articleCategories = $this->articleCategoryRepository->searchBack($request, $session, $data);
        shuffle($articleCategories);
        usort($articleCategories, function (ArticleCategory $a, ArticleCategory $b) {
            $routeA = array_reverse($a->getParentCategories());
            $routeA[] = $a;
            $routeB = array_reverse($b->getParentCategories());
            $routeB[] = $b;
            $common = null;
            foreach ($routeA as $key => $node) {
                if (isset($routeB[$key])) {
                    $common = $key;
                    if ($node->getPosition() != $routeB[$key]->getPosition()) {
                        return $node->getPosition() <=> $routeB[$key]->getPosition();
                    }
                } else {
                    break;
                }
            }
            if (isset($routeB[$common + 1]) && $routeA[$common] === $routeB[$common + 1]->getParentCategory()) {
                return -1;
            }

            if (isset($routeA[$common + 1]) && $routeB[$common] === $routeA[$common + 1]->getParentCategory()) {
                return 1;
            }

            dd($a->getName().' '.$b->getName());

            return 0;
        });
        $queryData = $this->articleCategoryManager->getQueryData($data);
        $formBatch = $this->createForm(ArticleCategoryBatchType::class, null, [
            'action' => $this->generateUrl('back_article_category_search', $queryData),
            'article_categories' => $articleCategories,
        ]);
        $formBatch->handleRequest($request);
        if ($formBatch->isSubmitted() && $formBatch->isValid()) {
            $url = $this->articleCategoryManager->dispatchBatchForm($formBatch);
            if ($url) {
                return $this->redirect($url);
            }
        }

        return $this->render('back/article_category/search/index.html.twig', [
            'article_categories' => $articleCategories,
            'form_filter' => $formFilter->createView(),
            'form_batch' => $formBatch->createView(),
            'form_delete' => $this->createFormBuilder()->getForm()->createView(),
            'query_data' => $queryData,
        ]);
    }

    /**
     * @Route("/create", name="back_article_category_create", methods="GET|POST")
     */
    public function create(Request $request): Response
    {
        $articleCategory = new ArticleCategory();
        $form = $this->createForm(ArticleCategoryType::class, $articleCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $last = false;
            if ($parent = $articleCategory->getParentCategory()) {
                $last = $parent->getSubcategories()->last();
            } else {
                $roots = $this->articleCategoryRepository->findRoots();
                $last = end($roots);
            }
            if ($last) {
                $articleCategory->setPosition($last->getPosition() + 1);
            }
            foreach ($form->get('articles')->getData() as $article) {
                $articlePositionCategory = new ArticlePositionCategory();
                $articleCategory->addPositionArticle($articlePositionCategory);
                $article->addPositionCategory($articlePositionCategory);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($articleCategory);
            $em->flush();
            $msg = $this->translator->trans('article_category.create.flash.success', ['%identifier%' => $articleCategory], 'back_messages');
            $this->addFlash('success', $msg);

            return $this->redirectToRoute('back_article_category_search');
        }

        return $this->render('back/article_category/create.html.twig', [
            'article_category' => $articleCategory,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/update/{id}", name="back_article_category_update", methods="GET|POST")
     */
    public function update(Request $request, ArticleCategory $articleCategory): Response
    {
        $oldParent = null;
        if ($articleCategory->getParentCategory()) {
            $oldParent = clone $articleCategory->getParentCategory();
        }
        $oldArticles = $articleCategory->getArticles();
        $form = $this->createForm(ArticleCategoryType::class, $articleCategory, ['articles' => $oldArticles]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($oldParent !== $articleCategory->getParentCategory()) {
                $last = false;
                if ($parent = $articleCategory->getParentCategory()) {
                    $last = $parent->getSubcategories()->last();
                } else {
                    $roots = $this->articleCategoryRepository->findRoots();
                    $last = end($roots);
                }
                if ($last) {
                    $articleCategory->setPosition($last->getPosition() + 1);
                }
            }
            $articles = $form->get('articles')->getData();
            foreach ($oldArticles as $article) {
                if (false === array_search($article, $articles, true)) {
                    $articleCategory->removeArticle($article);
                }
            }
            foreach ($articles as $article) {
                if (false === array_search($article, $oldArticles, true)) {
                    $articlePositionCategory = new ArticlePositionCategory();
                    $articleCategory->addPositionArticle($articlePositionCategory);
                    $article->addPositionCategory($articlePositionCategory);
                }
            }
            $this->getDoctrine()->getManager()->flush();
            $msg = $this->translator->trans('article_category.update.flash.success', [], 'back_messages');
            $this->addFlash('success', $msg);

            return $this->redirectToRoute('back_article_category_search');
        }

        return $this->render('back/article_category/update.html.twig', [
            'article_category' => $articleCategory,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete", name="back_article_category_delete", methods="GET|POST")
     */
    public function delete(Request $request): Response
    {
        $articleCategories = $this->articleCategoryManager->getArticleCategories();
        $formBuilder = $this->createFormBuilder();
        $formBuilder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) use ($articleCategories) {
            $result = $this->articleCategoryManager->validationDelete($articleCategories);
            if (true !== $result) {
                $event->getForm()->addError(new FormError($result));
            }
        });
        $form = $formBuilder->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            foreach ($articleCategories as $articleCategory) {
                $articleCategory->setParentCategory(null);
                if ($articleCategory->getSubcategories()->count()) {
                    $roots = $this->articleCategoryRepository->findRoots();
                    $last = end($roots);
                    $positionLast = -1;
                    if ($last) {
                        $positionLast = $last->getPosition();
                    }
                    foreach ($articleCategory->getSubcategories() as $subcategory) {
                        $subcategory->setPosition(++$positionLast);
                        $articleCategory->removeSubcategory($subcategory);
                    }
                }
                $em->remove($articleCategory);
            }
            try {
                $em->flush();

templates/back/article_category/search/_filter.html.twig
{% trans_default_domain 'back_messages' %}
<div class="card p-2 mb-2">
    <div class="card-body">
        {{ form_start(form_filter) }}
            <div class="row">
                <div class="col-lg-6">
                    {{ form_row(form_filter.search) }}
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <button id="filter_submit" class="btn btn-primary btn-block">
                            <i class="fas fa-filter"></i> {{ 'button.filter'|trans() }}
                        </button>
                    </div>
                </div>
            </div>
        {{ form_end(form_filter) }}
    </div>
</div>

templates/back/article_category/search/_list.html.twig
{% trans_default_domain 'back_messages' %}

{% set col_count = 2 %}

{% if can_multi_select %}
    {{ form_start(form_batch) }}
    {{ form_errors(form_batch) }}
{% endif %}
<div class="card mt-4 mb-4">
    <div class="card-body">
        <h2 class="card-title">{{ 'article_category.search.h2'|trans() }}</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        {% if can_multi_select %}
                            {% set col_count = col_count + 1 %}
                            <th>
                                <div class="form-check pl-0"><input type="checkbox" id="select_all"/></div>
                            </th>
                        {% endif %}
                        <th>{{ 'article_category.field.name'|trans() }}</th>
                        <th>{{ 'article_category.field.articles'|trans() }}</th>
                        <th>{{ 'article_category.field.displayed_home'|trans() }}</th>
                        <th>{{ 'article_category.field.displayed_menu'|trans() }}</th>
                        <th>{{ 'search.action_th'|trans() }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for child in form_batch.article_categories %}
                        {% set article_category = form_batch.article_categories.vars.choices[child.vars.value].data %}
                        <tr>
                            {% if can_multi_select %}
                                <td>
                                    {{ form_row(child, { 'attr': { 'class': 'select'}}) }}
                                </td>
                            {% endif %}
                            {% set pad_left = '' %}
                            {% if article_category.parentCategory %}
                                {% set pad_left = "%'-" ~ (article_category.deep + 1) ~ 's' %}
                                {% set pad_left = pad_left|format('>') %}
                            {% endif %}
                            <td>{{ pad_left ~ ' ' ~ article_category.name }}</td>
                            <td>
                                <br>
                                <ul class="list-unstyled">
                                    {% for article in article_category.articles %}
                                        <li>
                                            <a href="{{ path('back_article_read', { 'id': article.id }) }}">
                                                {{ article }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </td>
                            <td>{{ article_category.displayedHome ? 'yes'|trans : 'no'|trans }}</td>
                            <td>{{ article_category.displayedMenu ? 'yes'|trans : 'no'|trans }}</td>
                            <td>
                                {% if article_category.subcategories.count > 1 %}
                                    <a href="{{ path('back_article_category_order', { 'id': article_category.id }) }}" class="btn btn-primary">
                                        <i class="fas fa-plus"></i>
                                        {{ 'button.order'|trans() }}
                                    </a>
                                {% endif %}
                                {% if article_category.positionArticles.count > 1 %}
                                    <a href="{{ path('back_article_category_order_articles', { 'id': article_category.id }) }}" class="btn btn-primary">
                                        <i class="fas fa-plus"></i>
                                        {{ 'button.article_order'|trans() }}
                                    </a>
                                {% endif %}
                                {% if can_update %}
                                    <a href="{{ path('back_article_category_update', {'id': article_category.id}) }}" title="{{ 'button.update_title'|trans() }}" class="btn btn-warning" aria-label="{{ 'button.update_title'|trans() }}" role="button">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                {% endif %}
                                {% if can_delete %}
                                    <a href="#" class="btn btn-danger btn-delete" data-toggle="modal" data-target="#delete" data-title="{{ article_category }}" role="button" data-path="{{ path('back_article_category_delete', { 'ids': {0: article_category.id}}) }}" title="{{ 'button.delete_title'|trans() }}" aria-label="{{ 'button.delete_title'|trans() }}">
                                        <i class="fas fa-times"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="{{ col_count }}">{{ 'search.no_data_found'|trans() }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% if can_multi_select %}
    <div class="card p-2 mt-2">
        <div class="card-body">
            <div class="row">
                <div class="col-md-9 col-lg-9">
                    {{ form_row(form_batch.action) }}
                </div>
                <div class="col-md-3 col-lg-3">
                    <div class="text-center">
                        <button id="submit" class="btn btn-primary btn-block">{{ 'button.validate'|trans() }}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form_batch) }}
{% endif %}

templates/back/article_category/search/index.html.twig
{% trans_default_domain 'back_messages' %}
{% extends "back/layout.html.twig" %}

{% set can_create = true %}
{% set can_update = true %}
{% set can_delete = true %}
{% set can_filter = true %}
{% set can_multi_select = true %}

{% block title %}{{ 'article_category.search.title'|trans() }}{% endblock %}

{% block content %}
{% if can_delete %}
    <div id="delete" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modal_title" class="modal-title">{{ 'article_category.delete.modal_title'|trans() }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="X">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modal_body" class="modal-body">
                    <h6 id="modal_body_title"></h6>
                    <div class="alert alert-warning">
                        <strong>{{ 'delete.warning'|trans() }}</strong>
                    </div>
                </div>
                <div id="modal_footer" class="modal-footer">
                    {{ form_start(form_delete, {'attr': {'id': 'form_back_article_category_delete' }}) }}
                        <button type="submit" class="btn btn-danger">{{ 'button.delete'|trans() }}</button>
                    {{ form_end(form_delete) }}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'button.cancel'|trans() }}</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}
    <section class="pt-4 pb-4">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="h3">{{ 'article_category.search.h1'|trans() }}</h1>
                </div>
                <div class="col-sm-6 text-right">
                    <p>
                        {% if can_create %}
                            <a href="{{ path('back_article_category_create') }}" class="btn btn-primary">
                                <i class="fas fa-plus"></i> {{ 'button.create'|trans() }}
                            </a>
                        {% endif %}
                        <a href="{{ path('back_article_category_order') }}" class="btn btn-primary">
                            <i class="fas fa-plus"></i> {{ 'button.order'|trans() }}
                        </a>
                    </p>
                </div>
            </div>
            <hr>

            {% if can_filter %}
                {{ include('back/article_category/search/_filter.html.twig') }}
            {% endif %}

            {{ include('back/article_category/search/_list.html.twig') }}
        </div>
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    {% if can_delete %}
        <script>
            $(document).ready(function(){
                $('.btn-delete').click(function(){
                    var title = $(this).attr('data-title');
                    var path = $(this).attr('data-path');
                    $('#form_back_article_category_delete').attr('action', path);
                    $('#modal_body_title').html("{{ 'delete.confirm'|trans() }} : <strong>"+title+"</strong>");
                });
            });
        </script>
    {% endif %}

    {% if can_multi_select %}
        <script>
            $(document).ready(function(){
                $("#check_all").click(function(){
                    $('input:checkbox').not(this).prop('checked', this.checked);
                });
                $("#select_all").change(function() {
                    if (this.checked) {
                        $(".select").each(function() {
                            this.checked=true;
                        });
                    } else {
                        $(".select").each(function() {
                            this.checked=false;
                        });
                    }
                });
            });
        </script>
    {% endif %}

{% endblock %}